name: Send to PyScript

on:
  push:
    branches:
      - main

jobs:
  send_files_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send files to PyScript.com
        uses: FabioRosado/upload-to-pyscript@main
        with:
          api_token: ${{ secrets.PYSCRIPT_API_TOKEN }}
          project_id: '6382c36a-1503-4a2e-89f8-feaba9d4bd9d'
